import type { Task } from '@/types'

export const TASK_LIBRARY: Task[] = [
  // ── PHONE OUTREACH ──────────────────────────────────────────────────
  {
    id: 'phone-01',
    title: 'Cold Call 20 Local Restaurants',
    subtitle: 'Pitch website redesign or AI booking tools',
    type: 'phone',
    difficulty: 'medium',
    minutes: 60,
    money_impact: '$500–$2,000 potential',
    money_max: 2000,
    xp: 120,
    tip: 'Open with: "I noticed your Google reviews mention people having trouble finding your hours online — I fixed that for 3 restaurants this month."',
  },
  {
    id: 'phone-02',
    title: 'Follow Up With This Week\'s Leads',
    subtitle: 'Call everyone you spoke to in the last 7 days',
    type: 'phone',
    difficulty: 'easy',
    minutes: 30,
    money_impact: '$300–$1,500 potential',
    money_max: 1500,
    xp: 80,
    tip: '80% of sales happen after the 5th follow-up. Most people quit after 1.',
  },
  {
    id: 'phone-03',
    title: 'Call 15 Landscaping Companies',
    subtitle: 'Offer a free website audit and lead-gen setup',
    type: 'phone',
    difficulty: 'medium',
    minutes: 60,
    money_impact: '$500–$1,500 potential',
    money_max: 1500,
    xp: 120,
    tip: 'Ask if they\'re getting leads from their website. They almost never are.',
  },
  {
    id: 'phone-04',
    title: 'Call 10 Junk Removal Services',
    subtitle: 'Ask if they need more jobs booked this week',
    type: 'phone',
    difficulty: 'medium',
    minutes: 45,
    money_impact: '$400–$1,000 potential',
    money_max: 1000,
    xp: 100,
    tip: 'These guys need volume. Show them how you can fill their schedule in 2 weeks.',
  },
  {
    id: 'phone-05',
    title: 'Call 20 Local Cleaning Services',
    subtitle: 'Offer an AI review responder + booking page',
    type: 'phone',
    difficulty: 'medium',
    minutes: 60,
    money_impact: '$500–$2,000 potential',
    money_max: 2000,
    xp: 120,
    tip: 'Cleaning services have terrible online presence. They need you.',
  },
  {
    id: 'phone-06',
    title: 'Follow Up With 5 Ghosted Leads',
    subtitle: 'Send a text then call 30 minutes later',
    type: 'phone',
    difficulty: 'easy',
    minutes: 25,
    money_impact: '$200–$1,500 potential',
    money_max: 1500,
    xp: 70,
    tip: 'Text first: "Hey [name], just circling back — do you have 3 minutes today?" Then call.',
  },
  {
    id: 'phone-07',
    title: 'Call 10 HVAC or Plumbing Companies',
    subtitle: 'High-value trades that desperately need web leads',
    type: 'phone',
    difficulty: 'hard',
    minutes: 60,
    money_impact: '$800–$3,000 potential',
    money_max: 3000,
    xp: 200,
    tip: 'A plumber paying $0 for ads and getting 3 new jobs/week from your site = easy $1k/month retainer.',
  },
  {
    id: 'phone-08',
    title: 'Call 15 Local Salons or Barbers',
    subtitle: 'Pitch a booking widget + Google Business optimization',
    type: 'phone',
    difficulty: 'easy',
    minutes: 45,
    money_impact: '$300–$800 potential',
    money_max: 800,
    xp: 80,
    tip: 'Show them their Google ranking vs the salon 2 streets over.',
  },

  // ── DOOR-TO-DOOR ────────────────────────────────────────────────────
  {
    id: 'door-01',
    title: 'Knock 20 Houses — Junk Removal Quotes',
    subtitle: 'Drive 1 neighborhood. Offer free on-the-spot quotes.',
    type: 'door',
    difficulty: 'hard',
    minutes: 120,
    money_impact: '$100–$800 per job',
    money_max: 800,
    xp: 220,
    tip: 'Target houses with piled junk in the yard or recently renovated garages. Knock and say: "We\'re doing free junk removal quotes in the area today — got 5 minutes?"',
  },
  {
    id: 'door-02',
    title: 'Knock 20 Houses — Landscaping Quotes',
    subtitle: 'Walk the block, offer lawn care / cleanup pricing',
    type: 'door',
    difficulty: 'hard',
    minutes: 120,
    money_impact: '$80–$400 per job',
    money_max: 400,
    xp: 220,
    tip: 'Target overgrown lawns. Keep it direct: "We\'re quoting lawns on this street today — want a free price?"',
  },
  {
    id: 'door-03',
    title: 'Visit 10 Local Businesses — AI Agency Pitch',
    subtitle: 'Walk in with a printed 1-pager. Ask for the owner.',
    type: 'door',
    difficulty: 'hard',
    minutes: 90,
    money_impact: '$500–$2,000 per client',
    money_max: 2000,
    xp: 220,
    tip: 'Show them their Google listing vs a competitor who has a real website. Make it visual.',
  },
  {
    id: 'door-04',
    title: 'Knock 15 Houses — Pressure Washing Quotes',
    subtitle: 'Target driveways with visible staining / moss',
    type: 'door',
    difficulty: 'hard',
    minutes: 90,
    money_impact: '$150–$500 per job',
    money_max: 500,
    xp: 200,
    tip: 'Point to a specific dirty spot. Instant visual = instant sale. Quote on the spot.',
  },
  {
    id: 'door-05',
    title: 'Drop 50 Flyers — Cleaning Services',
    subtitle: 'Walk 2–3 streets with pre-printed flyers',
    type: 'door',
    difficulty: 'medium',
    minutes: 60,
    money_impact: '$100–$500 potential',
    money_max: 500,
    xp: 130,
    tip: 'Include a QR code to a Google Form for free quotes. Track which streets convert best.',
  },
  {
    id: 'door-06',
    title: 'Visit 8 Businesses — Free Website Audit',
    subtitle: 'Walk in with a printed screenshot of their bad Google presence',
    type: 'door',
    difficulty: 'hard',
    minutes: 90,
    money_impact: '$500–$1,500 per client',
    money_max: 1500,
    xp: 220,
    tip: 'Print their Google listing with a big red circle around a weak spot. It\'s hard to ignore.',
  },
  {
    id: 'door-07',
    title: 'Knock 25 Houses — Window Cleaning Quotes',
    subtitle: 'Spring / summer goldmine — easy yes rate',
    type: 'door',
    difficulty: 'medium',
    minutes: 90,
    money_impact: '$80–$250 per job',
    money_max: 250,
    xp: 160,
    tip: 'Direct ask: "We clean windows in the area for $80 — yours look like they\'re due. Want us to do them this week?"',
  },

  // ── ONLINE INCOME ───────────────────────────────────────────────────
  {
    id: 'online-01',
    title: 'DM 25 Local Businesses on Instagram',
    subtitle: 'Search [city] + [industry] and find businesses with weak presence',
    type: 'online',
    difficulty: 'medium',
    minutes: 45,
    money_impact: '$500–$2,000 potential',
    money_max: 2000,
    xp: 100,
    tip: 'Don\'t pitch in message 1. Just say: "Hey, I noticed you don\'t have a booking link in your bio — I could add one free. Want me to?" Easy foot in the door.',
  },
  {
    id: 'online-02',
    title: 'Research 3 Stocks — Write Notes',
    subtitle: 'Find 3 companies with earnings this week and build a thesis',
    type: 'online',
    difficulty: 'medium',
    minutes: 60,
    money_impact: 'Investing edge = compounding',
    money_max: 200,
    xp: 90,
    tip: 'Use finviz.com to filter by P/E, EPS growth, upcoming earnings. Look for patterns before you trade.',
  },
  {
    id: 'online-03',
    title: 'Send 20 Cold Emails to Local Businesses',
    subtitle: 'Use a template with their name, city, and a specific pain point',
    type: 'online',
    difficulty: 'medium',
    minutes: 45,
    money_impact: '$300–$2,000 potential',
    money_max: 2000,
    xp: 100,
    tip: 'Subject: "Your Google reviews are hiding your best customers, [Name]." — Gets 3x more opens.',
  },
  {
    id: 'online-04',
    title: 'List 5 Things on Facebook Marketplace',
    subtitle: 'Clear anything unused at home for quick cash',
    type: 'online',
    difficulty: 'easy',
    minutes: 30,
    money_impact: '$20–$200 same-day',
    money_max: 200,
    xp: 60,
    tip: 'Take photos in natural light. Price 20% below what others charge. Sell by tonight.',
  },
  {
    id: 'online-05',
    title: 'Post Value Content on LinkedIn',
    subtitle: 'Share a win, a lesson, or a local business story',
    type: 'online',
    difficulty: 'easy',
    minutes: 20,
    money_impact: 'Builds inbound pipeline',
    money_max: 0,
    xp: 50,
    tip: 'Write about a problem you solved for a local business. Real stories outperform advice posts 5x.',
  },
  {
    id: 'online-06',
    title: 'Research Dividend Stocks Under $10',
    subtitle: 'Find 2-3 that pay monthly dividends and have good coverage ratio',
    type: 'online',
    difficulty: 'medium',
    minutes: 45,
    money_impact: 'Passive income long-term',
    money_max: 100,
    xp: 80,
    tip: 'Look for REITs under $10 on Webull or Wealthsimple. Focus on payout ratio under 85%.',
  },
  {
    id: 'online-07',
    title: 'Build a Lead List of 30 Businesses',
    subtitle: 'Scrape Google Maps for businesses with no website',
    type: 'online',
    difficulty: 'medium',
    minutes: 60,
    money_impact: 'Fills your sales pipeline',
    money_max: 5000,
    xp: 90,
    tip: 'Search "[industry] in [city]" on Google Maps. Filter: "Doesn\'t have a website." These people need you NOW.',
  },
  {
    id: 'online-08',
    title: 'Reply to 10 Kijiji Junk Removal Posts',
    subtitle: 'People post "Need junk removed" every day',
    type: 'online',
    difficulty: 'easy',
    minutes: 20,
    money_impact: '$100–$500 per job',
    money_max: 500,
    xp: 70,
    tip: 'Message first wins. "Available today, free quote — what do you need removed?" Send in under 5 seconds.',
  },
  {
    id: 'online-09',
    title: 'Check Your Portfolio + Review Open Positions',
    subtitle: 'Evaluate stop-losses, targets, and upcoming earnings',
    type: 'online',
    difficulty: 'easy',
    minutes: 20,
    money_impact: 'Protect your capital',
    money_max: 0,
    xp: 40,
    tip: 'Set stop-loss at 7-8% below entry. Never let a trade become an investment by accident.',
  },
  {
    id: 'online-10',
    title: 'Post in 3 Local Facebook Groups',
    subtitle: 'Community groups, buy/sell groups, and local services groups',
    type: 'online',
    difficulty: 'easy',
    minutes: 20,
    money_impact: '$100–$400 potential',
    money_max: 400,
    xp: 60,
    tip: 'Don\'t post ads. Post: "Just finished a junk removal job down the street — anyone else need a quote?" Real + timely = gets responses.',
  },
  {
    id: 'online-11',
    title: 'Build One New Website Demo',
    subtitle: 'Mock up a fake site for a local business type',
    type: 'online',
    difficulty: 'hard',
    minutes: 120,
    money_impact: '$500–$2,000 per sale',
    money_max: 2000,
    xp: 200,
    tip: 'Build it on a cheap domain with their business name. When you show up with THEIR site already built, close rate triples.',
  },
  {
    id: 'online-12',
    title: 'Analyze 1 Market Chart + Write 3 Observations',
    subtitle: 'SPY, sector ETF, or individual stock you\'re watching',
    type: 'online',
    difficulty: 'medium',
    minutes: 30,
    money_impact: 'Sharpens your investing eye',
    money_max: 0,
    xp: 70,
    tip: 'Draw support, resistance, and note volume. Write it out in a notebook. Patterns stick better when written.',
  },

  // ── SKILL BUILDING ──────────────────────────────────────────────────
  {
    id: 'skill-01',
    title: 'Practice Your Sales Pitch Out Loud — 5 Times',
    subtitle: 'Record yourself on the last rep. Listen back.',
    type: 'skill',
    difficulty: 'medium',
    minutes: 30,
    money_impact: 'Closes more deals',
    money_max: 0,
    xp: 90,
    tip: 'Every stumble you hear is money you\'re losing. Fix it before a real call.',
  },
  {
    id: 'skill-02',
    title: 'Write 20 Objections + Your Responses',
    subtitle: '"Too expensive / Not right now / I\'ll think about it" — kill every one',
    type: 'skill',
    difficulty: 'medium',
    minutes: 30,
    money_impact: 'Removes deal-blocking friction',
    money_max: 0,
    xp: 90,
    tip: 'The objection you can\'t answer is the one killing your sales.',
  },
  {
    id: 'skill-03',
    title: 'Read 1 Chapter of a Sales Book',
    subtitle: 'Try: Way of the Wolf, Fanatical Prospecting, or $100M Offers',
    type: 'skill',
    difficulty: 'easy',
    minutes: 25,
    money_impact: 'Long-term income multiplier',
    money_max: 0,
    xp: 50,
    tip: 'Take 3 notes you can apply TODAY. Don\'t just read — extract actions.',
  },
  {
    id: 'skill-04',
    title: 'Practice Your Door-to-Door Opener',
    subtitle: 'Say your opening line in a mirror 15 times. Then out loud outside.',
    type: 'skill',
    difficulty: 'easy',
    minutes: 20,
    money_impact: 'The opener wins the door',
    money_max: 0,
    xp: 60,
    tip: 'If you hesitate at the door, you lose the sale before you start. Practice = confidence.',
  },
  {
    id: 'skill-05',
    title: 'Watch 1 Video on Local Business Sales Tactics',
    subtitle: 'YouTube: Alex Hormozi, Jeremy Miner, or Jordan Belfort',
    type: 'skill',
    difficulty: 'easy',
    minutes: 30,
    money_impact: 'Skill compounds over time',
    money_max: 0,
    xp: 50,
    tip: 'Watch with notes. Pause when you hear something powerful. Write it, test it today.',
  },
  {
    id: 'skill-06',
    title: 'Set Up Your CRM for the Week',
    subtitle: 'Update lead statuses, add follow-up dates, clean your list',
    type: 'skill',
    difficulty: 'easy',
    minutes: 20,
    money_impact: 'Never lose a lead again',
    money_max: 0,
    xp: 50,
    tip: 'A messy CRM loses money silently. Every missed follow-up is a dead deal.',
  },
  {
    id: 'skill-07',
    title: 'Create a 1-Page Pitch Sheet for Your Service',
    subtitle: 'Problem → Solution → Price → Result. 1 sheet. Printable.',
    type: 'skill',
    difficulty: 'medium',
    minutes: 45,
    money_impact: 'Professionalizes every meeting',
    money_max: 0,
    xp: 100,
    tip: 'If you can\'t explain what you do in 1 page, the client can\'t say yes.',
  },
  {
    id: 'skill-08',
    title: 'Study 1 Competing Service in Your Area',
    subtitle: 'Review their pricing, website, and Google reviews',
    type: 'skill',
    difficulty: 'easy',
    minutes: 25,
    money_impact: 'Win the edge on pricing and positioning',
    money_max: 0,
    xp: 60,
    tip: 'If they have bad reviews, those are YOUR leads. Use their pain points in your pitch.',
  },
  {
    id: 'skill-09',
    title: 'Write Your "Why You" Statement',
    subtitle: 'Why should someone hire YOU over everyone else in 30 seconds',
    type: 'skill',
    difficulty: 'medium',
    minutes: 30,
    money_impact: 'Wins the comparison conversation',
    money_max: 0,
    xp: 80,
    tip: 'It should mention speed, local trust, or a guarantee. Vague = forgettable.',
  },
  {
    id: 'skill-10',
    title: 'Learn One New Investing Concept',
    subtitle: 'Options basics, RSI, MACD, or reading earnings reports',
    type: 'skill',
    difficulty: 'medium',
    minutes: 40,
    money_impact: 'Protects and grows your capital',
    money_max: 0,
    xp: 80,
    tip: 'Invest $0 until you understand what you\'re buying. Education first.',
  },
]

export function getTaskById(id: string): Task | undefined {
  return TASK_LIBRARY.find(t => t.id === id)
}

export const TASK_TYPE_META: Record<string, { label: string; icon: string; color: string }> = {
  phone: { label: 'Phone', icon: '📞', color: '#3B82F6' },
  door:  { label: 'Door-to-Door', icon: '🚪', color: '#F97316' },
  online:{ label: 'Online', icon: '💻', color: '#8B5CF6' },
  skill: { label: 'Skill Build', icon: '🧠', color: '#10B981' },
}
